name: Development API Deploy

on:
    push:
        branches: main
    workflow_dispatch:

jobs:
    ssh-action-test:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Make Dot ENV
              env:
                  ENV: ${{secrets.TEST_ENV}}
              run: |
                  echo "${ENV}" > .env

            - name: File SCP
              uses: appleboy/scp-action@master
              with:
                  host: ${{secrets.TEST_HOST}}
                  username: ${{secrets.TEST_USERNAME}}
                  key: ${{secrets.TEST_PRIVATE_KEY}}
                  source: ".env"
                  target: "/home/ec2-user"

            - name: SSH Action
              uses: appleboy/ssh-action@v1.0.3
              env:
                  IMAGE_NAME: cloudcoke/sample-node:latest
                  CONTAINER_PORT: ${{ secrets.TEST_IMAGE_PORT }}
                  CONTAINER_NAME: ${{ secrets.TEST_CONTAINER_NAME }}
                  ENV_FILE: .env
                  AWSLOGS_REGION: ap-northeast-2
                  AWSLOGS_GROUP: ${{ secrets.TEST_AWSLOGS_GROUP }}
              with:
                  host: ${{ secrets.TEST_HOST }}
                  username: ${{ secrets.TEST_USERNAME }}
                  key: ${{ secrets.TEST_PRIVATE_KEY }}
                  port: 22
                  envs: IMAGE_NAME,CONTAINER_PORT,CONTAINER_NAME,ENV_FILE,AWSLOGS_REGION,AWSLOGS_GROUP
                  script_stop: true
                  script: bash deploy.sh -n $CONTAINER_NAME -i $IMAGE_NAME --env-file $ENV_FILE -p $CONTAINER_PORT \
                      --log-driver awslogs --log-opt awslogs-region=$AWSLOGS_REGION --log-opt awslogs-group=$AWSLOGS_GROUP --log-opt awslogs-create-group=true
                  #   script: echo "-n $CONTAINER_NAME -i $IMAGE_NAME --env-file $ENV_FILE -p $CONTAINER_PORT \
                  #       --log-driver awslogs --log-opt awslogs-region=$AWSLOGS_REGION --log-opt awslogs-group=$AWSLOGS_GROUP --log-opt awslogs-create-group=true" > test.txt
